name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: do-leecode
      DEPLOY_REPO: do-leecode.github.io
      DEPLOY_BRANCH: main
      GIT_USER: do-leecode
      GIT_EMAIL: 626692024@qq.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0
      
      - name: Set timezone to Asia/Shanghai
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Echo current time
        run: timedatectl

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.1

      - name: Generate pages
        run: |
          export TZ='Asia/Shanghai'
          git config --global user.email "626692024@qq.com"
          git config --global user.name "reganzm"
          npm install --save
          npm install hexo-cli -g
          hexo clean && hexo g && hexo d
      
